### PR TITLE
feat: Initial implementation of pathbuilder import

### PR DESCRIPTION
**Pull request by scooper4711**
## Pull Request Description

Add the ability to import PCs (and NPCs) from [Pathbuilder2e](https://pathbuilder2e.com)

## Changes Proposed

- [ ] Added new class - PathbuilderImport.ts - does the main lifting of the import
- [ ] Added new class - Pathbuilder.d.ts - defines the datastructure of the JSON output by pathbuilder2e
- [ ] Added the export keyword on a few methods in pf2eMonsterToolImport.ts for consistent formatting and code reuse.
- [ ] Added code to the import worker to handle Pathbuilder
- [ ] Added code to the settings to allow for importing Pathbuilder

## Related Issues

Fixes - #448 

## Checklist

- [X] I have read the contribution guidelines and code of conduct.
- [X] I have tested the changes locally and they are working as expected.
- [X] I have added appropriate comments and documentation for the code changes.
- [X] My code follows the coding style and standards of this project.
- [X] I have rebased my branch on the latest main (or master) branch.
- [X] All tests (if applicable) have passed successfully.
- [X] I have run linters and fixed any issues.
- [X] I have checked for any potential security issues or vulnerabilities.

## Screenshots (if applicable)

image

## Additional Notes

The intent here is to have a quick reference for the GM for all the shenanigans that a Player gets up to, so the emphasis has been on listing and linking all feats, spells and items. 

Pathbuilder makes no distinction in its data structure between melee and ranged weapons. I have them all listed as 'Melee" because that's closer to a normal bestiary card, but was debating replacing that with the word "attack" or "weapon". 

I specify the json file as the source. Not sure if that's what you intended. I'm thinking that the next feature I want to add is to have the program prompt for a JSON id (a pathbuilder concept) and then the importer makes a restful API call to fetch the JSON without the need for the GM first storing the data on disk and then loading that file. Then the source would be the JSON id. (for an even more future possibility of a refresh enhancement).

Hope you like the code - more than willing to make adjustments.

### CODE REVIEW

**Comment by scooper4711** [comment]
Don’t merge yet - I just thought of how I want to change [[Scroll of Spell]] to Scroll of [[Spell]]

**Comment by scooper4711** [comment]
Ok - fixed Potion of, Wand of, and Scroll of. Should now link to the spell.

**Comment by scooper4711** [comment]
I'm not sure why, but this branch of code doesn't render traits as hyperlinks. e.g. 
`trait_01: evil` renders as ((evil)) instead of a hyperlink to the traits evil.

**Comment by scooper4711** [comment]
All issues resolved to my knowledge. Please review.

**Review by valentine195 — APPROVED** [review]

**Pull request merged**
