### PR TITLE
✨docs: Updates to Layout Folders to Streamline Submission Process

### PR DESCRIPTION
**Pull request by sigrunixia**
chore: Created publish, publish/image(s), xCSS, callback, and other folders in each src/layout folder.
feat: Created sample-readme.md and your-layout.ts to offload some of the tedious manual work onto submitter, while also minimizing errors on both ends.
chore: Updated links in relation to the changes above.

Signed-off-by: Sigrunixia <Scholarlysigrun@icloud.com>

### CODE REVIEW

**Comment by sigrunixia** [comment]
Added a contributing.md and code-of-conduct (Since it was recommended along with it) I know the second is not really needed now. Better it's there now. 

Contribuding.md needs one small part filled out:

```
### Your First Code Contribution
<!-- TODO
include Setup of env, IDE and typical getting started instructions?

-->
```

**Comment by valentine195** [comment]
Good reference for building from source: https://github.com/fantasycalendar/obsidian-fantasy-calendar/pull/121

**Comment by sigrunixia** [comment]
> Good reference for building from source: [fantasycalendar/obsidian-fantasy-calendar#121](https://github.com/fantasycalendar/obsidian-fantasy-calendar/pull/121)

Added a reworded form of this both to contributing.md and the documentation/plugin-management area.

**Comment by sigrunixia** [comment]
Taking this out of draft just so we can start coordinating later.

**Comment by sigrunixia** [comment]
Okay Fixed this to be JUST about the changes in directory layouts and publish-related things, but contributing.md and code-of-conduct.md. 

Any problems with the two files for now @valentine195?

**Pull request merged**
